"""Route handlers for the radiolens inference API."""

from __future__ import annotations

from pathlib import Path

import structlog
from fastapi import APIRouter, Depends, File, HTTPException, UploadFile

from radiolens import __version__
from radiolens.api.contracts import (
    ClassificationResponse,
    HealthStatus,
    ModelInfo,
    PerformanceStats,
)
from radiolens.api.providers import (
    get_uptime,
    provide_classifier,
    provide_settings,
)
from radiolens.config import Settings
from radiolens.core.detector import ThoraxClassifier
from radiolens.core.preprocessor import ImageNormalizer

log = structlog.get_logger(__name__)

router = APIRouter()

_CLINICAL_NOTE: str = (
    "RESEARCH USE ONLY. This output is generated by an experimental AI "
    "system and must NOT be used as a substitute for professional medical "
    "diagnosis. Always consult a qualified radiologist or clinician."
)

_DICOM_SUFFIX: str = ".dcm"
_SUPPORTED_IMAGE_SUFFIXES: frozenset[str] = frozenset(
    {".jpeg", ".jpg", ".png", _DICOM_SUFFIX}
)


def _provide_normalizer(
    settings: Settings = Depends(provide_settings),
) -> ImageNormalizer:
    """FastAPI dependency: construct an ImageNormalizer from settings.

    Args:
        settings: Injected settings instance.

    Returns:
        A fresh :class:`~radiolens.core.preprocessor.ImageNormalizer`.
    """
    return ImageNormalizer(settings)


@router.post("/classify", response_model=ClassificationResponse)
async def classify_radiograph(
    file: UploadFile = File(...),
    classifier: ThoraxClassifier = Depends(provide_classifier),
    settings: Settings = Depends(provide_settings),
    normalizer: ImageNormalizer = Depends(_provide_normalizer),
) -> ClassificationResponse:
    """Accept a chest X-ray image and return a pneumonia classification.

    Supported file types: JPEG, PNG, DICOM (``.dcm``).

    Args:
        file: Uploaded image file.
        classifier: Injected :class:`ThoraxClassifier`.
        settings: Injected :class:`Settings`.
        normalizer: Injected :class:`ImageNormalizer`.

    Returns:
        A :class:`ClassificationResponse` with label, probability,
        confidence, certainty tier, and a clinical disclaimer.

    Raises:
        HTTPException: 400 for unsupported file types.
        HTTPException: 422 for files that cannot be decoded.
    """
    filename = file.filename or ""
    suffix = Path(filename).suffix.lower()

    if suffix not in _SUPPORTED_IMAGE_SUFFIXES:
        log.warning(
            "unsupported_file_type",
            filename=filename,
            suffix=suffix,
        )
        raise HTTPException(
            status_code=400,
            detail=(
                f"Unsupported file type '{suffix}'. "
                f"Accepted: {sorted(_SUPPORTED_IMAGE_SUFFIXES)}"
            ),
        )

    raw_bytes = await file.read()

    try:
        if suffix == _DICOM_SUFFIX:
            import tempfile

            from radiolens.data.dicom_reader import read_dicom_as_pil

            with tempfile.NamedTemporaryFile(
                suffix=".dcm", delete=False
            ) as tmp:
                tmp.write(raw_bytes)
                tmp_path = Path(tmp.name)

            try:
                pil_image = read_dicom_as_pil(tmp_path)
            finally:
                tmp_path.unlink(missing_ok=True)

            pixel_array = normalizer.from_pil(pil_image)
        else:
            pixel_array = normalizer.from_bytes(raw_bytes)
    except (ValueError, OSError) as exc:
        log.warning(
            "image_decode_failed",
            filename=filename,
            error=str(exc),
        )
        raise HTTPException(
            status_code=422,
            detail=f"Cannot decode image '{filename}': {exc}",
        ) from exc

    result = classifier.run_inference(pixel_array)

    log.info(
        "classify_request",
        filename=filename,
        label=result.label,
        confidence=round(result.confidence, 4),
        certainty_tier=result.certainty_tier,
    )

    return ClassificationResponse(
        label=result.label,
        probability=result.probability,
        confidence=result.confidence,
        certainty_tier=result.certainty_tier,
        clinical_note=_CLINICAL_NOTE,
        model_version=__version__,
    )


@router.get("/health", response_model=HealthStatus)
async def health_check(
    uptime: float = Depends(get_uptime),
) -> HealthStatus:
    """Return service health status.

    Args:
        uptime: Injected uptime in seconds.

    Returns:
        A :class:`HealthStatus` indicating whether the model is loaded.
    """
    from radiolens.api.providers import _classifier_instance

    model_loaded = _classifier_instance is not None
    return HealthStatus(
        status="healthy" if model_loaded else "degraded",
        model_loaded=model_loaded,
        uptime_seconds=round(uptime, 2),
        version=__version__,
    )


@router.get("/info", response_model=ModelInfo)
async def model_information(
    settings: Settings = Depends(provide_settings),
) -> ModelInfo:
    """Return model architecture and validation metadata.

    Args:
        settings: Injected :class:`Settings`.

    Returns:
        A :class:`ModelInfo` describing the deployed model.
    """
    h, w, c = (
        settings.image_height,
        settings.image_width,
        settings.image_channels,
    )
    return ModelInfo(
        backbone=settings.backbone_name,
        input_shape=[h, w, c],
        output_classes=["NORMAL", "PNEUMONIA"],
        training_dataset=(
            "Kaggle Chest X-Ray Images (Pneumonia) — "
            "Guangzhou Women and Children's Medical Centre"
        ),
        validation_approach=(
            "Stratified 70/20/10 internal split + "
            "cross-operator validation on an independent dataset"
        ),
        cross_operator_accuracy=0.860,
        cross_operator_sensitivity=0.964,
        cross_operator_auc=0.964,
    )


@router.get("/performance", response_model=PerformanceStats)
async def performance_statistics() -> PerformanceStats:
    """Return cross-operator validation metrics from the publication.

    Metrics are derived from the published research results:

    - Internal: accuracy=0.948, sensitivity=0.896, specificity=1.000,
      AUC=0.988
    - External: accuracy=0.860, sensitivity=0.964, specificity=0.748,
      AUC=0.964
    - Bootstrap 95 % CI for ΔAUC: [−0.0115, 0.0099], p=0.978

    Returns:
        A :class:`PerformanceStats` with all published metric values.
    """
    return PerformanceStats(
        internal_accuracy=0.948,
        internal_sensitivity=0.896,
        internal_specificity=1.000,
        internal_roc_auc=0.988,
        external_accuracy=0.860,
        external_sensitivity=0.964,
        external_specificity=0.748,
        external_roc_auc=0.964,
        bootstrap_p_value=0.978,
        bootstrap_ci_lower=-0.0115,
        bootstrap_ci_upper=0.0099,
        n_external_samples=107,
    )
