"""Streamlit web dashboard for interactive radiolens inference."""

from __future__ import annotations

import io
import sys
import tempfile
from pathlib import Path

# Allow running without a package install
sys.path.insert(
    0,
    str(Path(__file__).resolve().parents[1] / "src"),
)

import numpy as np
import streamlit as st
from PIL import Image

from radiolens.config import get_settings
from radiolens.core.detector import ThoraxClassifier
from radiolens.core.preprocessor import ImageNormalizer

# ------------------------------------------------------------------ Constants

_DICOM_SUFFIX: str = ".dcm"
_ACCEPTED_UPLOAD_TYPES: list[str] = ["jpg", "jpeg", "png", "dcm"]

_CLINICAL_DISCLAIMER: str = (
    "**DISCLAIMER — RESEARCH USE ONLY.**  "
    "This tool is an experimental AI research prototype and must **NOT** "
    "be used as a substitute for professional medical diagnosis.  "
    "All outputs require review by a qualified radiologist or clinician."
)

_CERTAINTY_COLORS: dict[str, str] = {
    "HIGH": "green",
    "MODERATE": "orange",
    "LOW": "red",
}


# ------------------------------------------------------------- Cached loaders


@st.cache_resource(show_spinner="Loading radiolens model…")
def _load_classifier() -> ThoraxClassifier:
    """Load and cache the ThoraxClassifier singleton.

    Returns:
        Initialised :class:`~radiolens.core.detector.ThoraxClassifier`.
    """
    settings = get_settings()
    clf = ThoraxClassifier(settings)
    clf.load_weights(settings.model_weights_path)
    return clf


@st.cache_resource
def _load_normalizer() -> ImageNormalizer:
    """Return a cached ImageNormalizer instance.

    Returns:
        :class:`~radiolens.core.preprocessor.ImageNormalizer`.
    """
    return ImageNormalizer(get_settings())


# ----------------------------------------------------------------- PDF report


def _generate_pdf_report(
    label: str,
    probability: float,
    confidence: float,
    certainty_tier: str,
    image_bytes: bytes,
    image_filename: str,
) -> bytes:
    """Generate a clinical-style PDF report using fpdf2.

    Args:
        label: Predicted class label.
        probability: Sigmoid output probability.
        confidence: max(prob, 1-prob).
        certainty_tier: ``"HIGH"``, ``"MODERATE"``, or ``"LOW"``.
        image_bytes: Raw bytes of the uploaded image.
        image_filename: Original file name for the report header.

    Returns:
        PDF file content as bytes.
    """
    try:
        from fpdf import FPDF  # type: ignore[import]
    except ImportError as exc:
        raise ImportError(
            "fpdf2 is required for PDF export. "
            "Install it with: pip install fpdf2"
        ) from exc

    pdf = FPDF()
    pdf.set_margins(left=15, top=15, right=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "radiolens — Chest X-Ray Analysis Report", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(
        0,
        6,
        "RESEARCH USE ONLY — Not for clinical decision-making",
        ln=True,
    )
    pdf.ln(4)

    # Divider
    pdf.set_draw_color(180, 180, 180)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(4)

    # Left column — metadata
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(90, 8, "Classification Result", ln=False)
    pdf.cell(0, 8, "Image", ln=True)

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(90, 7, f"File: {image_filename}", ln=False)
    pdf.ln(7)

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*(_get_rgb_for_label(label)))
    pdf.cell(90, 9, f"Prediction: {label}", ln=False)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(9)

    pdf.set_font("Helvetica", "", 11)
    for key, value in [
        ("Probability", f"{probability:.4f}"),
        ("Confidence", f"{confidence:.4f}"),
        ("Certainty Tier", certainty_tier),
    ]:
        pdf.cell(90, 7, f"{key}: {value}", ln=True)

    # Image inset (right column)
    try:
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            pil = Image.open(io.BytesIO(image_bytes)).convert("RGB")
            pil.save(tmp.name, format="PNG")
            tmp_path = tmp.name
        pdf.image(tmp_path, x=110, y=50, w=80)
        Path(tmp_path).unlink(missing_ok=True)
    except Exception:
        pass  # Image embedding is best-effort

    pdf.ln(8)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(5)

    # Disclaimer
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(
        0,
        5,
        (
            "DISCLAIMER: This report is generated by an experimental AI "
            "system for research purposes only. It has not been approved "
            "for clinical use and must not substitute professional medical "
            "diagnosis. All findings require review by a qualified "
            "radiologist or clinician."
        ),
    )
    pdf.set_text_color(0, 0, 0)

    return pdf.output()


def _get_rgb_for_label(label: str) -> tuple[int, int, int]:
    """Return an RGB tuple for a given prediction label.

    Args:
        label: ``"PNEUMONIA"`` or ``"NORMAL"``.

    Returns:
        RGB tuple used for coloured text in the PDF report.
    """
    if label == "PNEUMONIA":
        return (200, 30, 30)
    return (30, 140, 30)


# -------------------------------------------------------------------- Main UI


def main() -> None:
    """Run the Streamlit dashboard application."""
    st.set_page_config(
        page_title="radiolens — Chest X-Ray AI",
        page_icon="🫁",
        layout="wide",
    )

    st.title("radiolens — Chest X-Ray Pneumonia Detection")
    st.caption(
        "MobileNetV2 transfer learning | Research prototype "
        "| Not for clinical use"
    )

    # -------------------------------------------------- Sidebar performance
    with st.sidebar:
        st.header("Published Performance")
        with st.expander("Internal Validation", expanded=True):
            st.metric("Accuracy", "94.8%")
            st.metric("Sensitivity", "89.6%")
            st.metric("Specificity", "100.0%")
            st.metric("ROC-AUC", "0.988")

        with st.expander("Cross-Operator (External)", expanded=True):
            st.metric("Accuracy", "86.0%")
            st.metric("Sensitivity", "96.4%")
            st.metric("Specificity", "74.8%")
            st.metric("ROC-AUC", "0.964")

        with st.expander("Bootstrap Statistics"):
            st.write("**95% CI for ΔAUC:** [−0.0115, 0.0099]")
            st.write("**p-value:** 0.978")
            st.write("**n (external):** 107")

        st.divider()
        st.caption(_CLINICAL_DISCLAIMER)

    # ------------------------------------------------- File upload
    uploaded = st.file_uploader(
        "Upload a chest X-ray image",
        type=_ACCEPTED_UPLOAD_TYPES,
        help="Accepts JPEG, PNG, and DICOM (.dcm) files.",
    )

    if uploaded is None:
        st.info(
            "Upload a chest X-ray image to begin analysis.",
            icon="📂",
        )
        return

    raw_bytes = uploaded.read()
    filename = uploaded.name or "uploaded_file"
    suffix = Path(filename).suffix.lower()

    # ------------------------------------------------- Decode image
    pixel_array: np.ndarray | None = None
    pil_image: Image.Image | None = None

    normalizer = _load_normalizer()

    with st.spinner("Decoding image…"):
        try:
            if suffix == _DICOM_SUFFIX:
                from radiolens.data.dicom_reader import read_dicom_as_pil

                with tempfile.NamedTemporaryFile(
                    suffix=".dcm", delete=False
                ) as tmp:
                    tmp.write(raw_bytes)
                    tmp_path = Path(tmp.name)

                try:
                    pil_image = read_dicom_as_pil(tmp_path)
                finally:
                    tmp_path.unlink(missing_ok=True)

                pixel_array = normalizer.from_pil(pil_image)
            else:
                pixel_array = normalizer.from_bytes(raw_bytes)
                pil_image = Image.open(io.BytesIO(raw_bytes)).convert("RGB")
        except (ValueError, FileNotFoundError) as exc:
            st.error(
                f"Could not decode '{filename}': {exc}",
                icon="⚠️",
            )
            return

    # ------------------------------------------------- Run inference
    with st.spinner("Running inference…"):
        try:
            classifier = _load_classifier()
            result = classifier.run_inference(pixel_array)
        except (RuntimeError, FileNotFoundError) as exc:
            st.error(
                f"Inference failed: {exc}",
                icon="⚠️",
            )
            return

    # ------------------------------------------------- Display results
    col_img, col_result = st.columns([1, 1], gap="large")

    with col_img:
        st.subheader("Uploaded Image")
        if pil_image is not None:
            st.image(pil_image, use_column_width=True, caption=filename)

    with col_result:
        st.subheader("Analysis Result")

        label_color = "red" if result.label == "PNEUMONIA" else "green"
        st.markdown(f"### :{label_color}[{result.label}]")

        tier_color = _CERTAINTY_COLORS.get(result.certainty_tier, "grey")
        st.markdown(f"**Certainty:** :{tier_color}[{result.certainty_tier}]")

        st.write("**Confidence**")
        st.progress(
            result.confidence,
            text=f"{result.confidence:.1%}",
        )

        st.metric(
            label="Pneumonia probability",
            value=f"{result.probability:.4f}",
        )
        st.metric(
            label="Confidence score",
            value=f"{result.confidence:.4f}",
        )

        st.divider()

        # PDF download
        try:
            pdf_bytes = _generate_pdf_report(
                label=result.label,
                probability=result.probability,
                confidence=result.confidence,
                certainty_tier=result.certainty_tier,
                image_bytes=raw_bytes,
                image_filename=filename,
            )
            st.download_button(
                label="Download PDF Report",
                data=bytes(pdf_bytes),
                file_name="radiolens_report.pdf",
                mime="application/pdf",
                use_container_width=True,
            )
        except ImportError:
            st.caption("Install `fpdf2` to enable PDF report downloads.")

    # ------------------------------------------------- Disclaimer footer
    st.divider()
    st.warning(_CLINICAL_DISCLAIMER, icon="⚠️")


if __name__ == "__main__":
    main()
